

package org.usfirst.frc6979.FRC2018;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	
    public static WPI_TalonSRX drivefrontLeft;
    public static WPI_TalonSRX drivebackLeft;
    public static SpeedControllerGroup driveLeft;
    public static WPI_TalonSRX drivefrontRight;
    public static WPI_TalonSRX drivebackRight;
    public static SpeedControllerGroup driveRight;
    public static DifferentialDrive driveDifferentialDrive;
    
    public static DigitalInput elevatorHighLimit;
    public static WPI_TalonSRX elevatorElevator;
    public static DigitalInput elevatorLowLimit;



    public static void init() {
    	
    	/*
    	 * 
    	 * 
    	 */
    	
    	/*TODO:
    	 * - Fix depreciated telemetry
    	 * 
    	 */
    	
    	
    	/*
    	 * INSTANTIATE DRIVE
    	 */
    	// Instantiate left Speed Controller group
        drivefrontLeft = new WPI_TalonSRX(0);
        drivebackLeft = new WPI_TalonSRX(2);
        driveLeft = new SpeedControllerGroup(drivefrontLeft, drivebackLeft  );
        //LiveWindow.addActuator("Drive", "d_Left", drived_Left);
        
        // Instantiate right Speed Controller group
        drivefrontRight = new WPI_TalonSRX(1);
        drivebackRight = new WPI_TalonSRX(3);
        driveRight = new SpeedControllerGroup(drivefrontRight, drivebackRight  );
        //LiveWindow.addActuator("Drive", "d_Right", drived_Right);
        
        // Instantiate Differential Drive
        driveDifferentialDrive = new DifferentialDrive(driveLeft, driveRight);
        //LiveWindow.addActuator("Drive", "Differential Drive", driveDifferentialDrive);
        
        // Differential Drive Set-Up
        driveDifferentialDrive.setSafetyEnabled(true);
        driveDifferentialDrive.setExpiration(0.1);
        driveDifferentialDrive.setMaxOutput(1.0);
        
        
        /*
         * INSTANTIATE ELEVATOR IO
         */
        
        // Elevator Speed Controller
        elevatorElevator = new WPI_TalonSRX(4);
        // Elevator High Limit Switch
        elevatorHighLimit = new DigitalInput(1);
        //LiveWindow.addSensor("Elevator", "topElevLimit", elevatortopElevLimit);
        //Elevator Low Limit Switch
        elevatorLowLimit = new DigitalInput(0);
        //LiveWindow.addSensor("Elevator", "bottomElevLimit", elevatorbottomElevLimit);
        


    }
}
