

package org.usfirst.frc6979.FRC2018;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	
	//Left Drive
    public static WPI_TalonSRX driveFrontLeft;
    public static WPI_TalonSRX driveBackLeft;
    public static SpeedControllerGroup driveLeft;
    
    //Right Drive
    public static WPI_TalonSRX driveFrontRight;
    public static WPI_TalonSRX driveBackRight;
    public static SpeedControllerGroup driveRight;
    
    public static DifferentialDrive driveDifferentialDrive;
    
    //Elevator
    public static DigitalInput elevatorHighLimit;
    public static WPI_TalonSRX elevator;
    public static DigitalInput elevatorLowLimit;
    
    //Lift
    public static DigitalInput liftHighLimit;
    public static Spark lift;
    public static DigitalInput liftLowLimit;
    
    //Arms
    public static WPI_TalonSRX leftArm;
    
    public static WPI_TalonSRX rightArm;

    //Pneumatic Systems for Arm
    public static Compressor compressorArm = new Compressor(8);
    public static DoubleSolenoid solenoidArm = new DoubleSolenoid(8, 0, 1);
    
    //Other
    public static WPI_TalonSRX winchMotor;
    

    public static void init() {
    	
    	/*TODO:
    	 * - Fix depreciated telemetry
    	 * 
    	 */
    	
    	
    	
    	/*
    	 * INSTANTIATE DRIVE
    	 */
    	// Instantiate left Speed Controller group
        driveFrontLeft = new WPI_TalonSRX(8);
        driveBackLeft = new WPI_TalonSRX(2);
        driveLeft = new SpeedControllerGroup(driveFrontLeft, driveBackLeft  );
        	//LiveWindow.addActuator("Drive", "d_Left", drived_Left);
        
        // Instantiate right Speed Controller group
        driveFrontRight = new WPI_TalonSRX(4);
        driveBackRight = new WPI_TalonSRX(3);
        driveRight = new SpeedControllerGroup(driveFrontRight, driveBackRight  );
        
      	//LiveWindow.addActuator("Drive", "d_Right", drived_Right);

        
        // Instantiate Differential Drive
        driveDifferentialDrive = new DifferentialDrive(driveLeft, driveRight);
        	//LiveWindow.addActuator("Drive", "Differential Drive", driveDifferentialDrive);
        
        // Differential Drive Parameters
        driveDifferentialDrive.setSafetyEnabled(true);
        driveDifferentialDrive.setExpiration(0.1);
        driveDifferentialDrive.setMaxOutput(1.0);
        
        
        
        
        /*
         * INSTANTIATE ELEVATOR IO
         */
        
        // Elevator Speed Controller
        elevator = new WPI_TalonSRX(6);
        
        // Elevator High Limit Switch
        elevatorHighLimit = new DigitalInput(5);
        //LiveWindow.addSensor("Elevator", "topElevLimit", elevatortopElevLimit);
        
        //Elevator Low Limit Switch
        //elevatorLowLimit = new DigitalInput(1);
        //LiveWindow.addSensor("Elevator", "bottomElevLimit", elevatorbottomElevLimit);

        
        
        
        
        /*
         * INSTANTIATE LIFT IO
         */
        
        //Lift Speed Controller
        lift = new Spark(0);
        
        //Lift High Limit Switch
        liftHighLimit = new DigitalInput(3);
        //LiveWindow.addSensor("Elevator", "topElevLimit", elevatortopElevLimit);
        
        //Lift Low Limit Switch
        liftLowLimit = new DigitalInput(1);
        //LiveWindow.addSensor("Elevator", "bottomElevLimit", elevatorbottomElevLimit);
        
        
        //Winch
        winchMotor = new WPI_TalonSRX(1); //TODO: Make sure this is in BRAKE MODE
        
        
        /*
         * INSTANTIATE ARMS IO
         */
        
        //Arm Speed Controllers
        leftArm = new WPI_TalonSRX(7);
        
        rightArm = new WPI_TalonSRX(5);
        rightArm.setInverted(true);
        rightArm.follow(leftArm); 
        
        
        //When true, PCM automatically turns on compressor when pressure switch is closed
        compressorArm.setClosedLoopControl(true);
        compressorArm.start();
    }
}
