

package org.usfirst.frc6979.FRC2018;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	
	//Left Drive
    public static WPI_TalonSRX driveFrontLeft;
    public static WPI_TalonSRX driveBackLeft;
    public static SpeedControllerGroup driveLeft;
    
    //Right Drive
    public static WPI_TalonSRX driveFrontRight;
    public static WPI_TalonSRX driveBackRight;
    public static SpeedControllerGroup driveRight;
    
    public static DifferentialDrive driveDifferentialDrive;
    
    //Elevator
    public static DigitalInput elevatorHighLimit;
    public static WPI_TalonSRX elevator;
    public static DigitalInput elevatorLowLimit;
    
    //Lift
    public static DigitalInput liftHighLimit;
    public static WPI_TalonSRX lift;
    public static DigitalInput liftLowLimit;
    
    //Arms
    public static WPI_TalonSRX leftArm;
    public static WPI_TalonSRX rightArm;
    
    //Other
    public static Spark winchMotor;
    

    public static void init() {
    	
    	/*TODO:
    	 * - Fix depreciated telemetry
    	 * 
    	 */
    	
    	/*
    	 * INSTANTIATE DRIVE
    	 */
    	// Instantiate left Speed Controller group
        driveFrontLeft = new WPI_TalonSRX(0);
        driveBackLeft = new WPI_TalonSRX(2);
        driveLeft = new SpeedControllerGroup(driveFrontLeft, driveBackLeft  );
        	//LiveWindow.addActuator("Drive", "d_Left", drived_Left);
        
        // Instantiate right Speed Controller group
        driveFrontRight = new WPI_TalonSRX(4);
        driveBackRight = new WPI_TalonSRX(3);
        driveRight = new SpeedControllerGroup(driveFrontRight, driveBackRight  );
        
      	//LiveWindow.addActuator("Drive", "d_Right", drived_Right);
        //Set neutral mode for speed controllers
        driveFrontLeft.setNeutralMode(com.ctre.phoenix.motorcontrol.NeutralMode.Brake);
        driveBackLeft.setNeutralMode(com.ctre.phoenix.motorcontrol.NeutralMode.Brake);
        driveFrontRight.setNeutralMode(com.ctre.phoenix.motorcontrol.NeutralMode.Brake);
        driveBackRight.setNeutralMode(com.ctre.phoenix.motorcontrol.NeutralMode.Brake);
        
        // Instantiate Differential Drive
        driveDifferentialDrive = new DifferentialDrive(driveLeft, driveRight);
        	//LiveWindow.addActuator("Drive", "Differential Drive", driveDifferentialDrive);
        
        // Differential Drive Parameters
        driveDifferentialDrive.setSafetyEnabled(true);
        driveDifferentialDrive.setExpiration(0.1);
        driveDifferentialDrive.setMaxOutput(1.0);
        
        /*
         * INSTANTIATE ELEVATOR IO
         */
        
        // Elevator Speed Controller
        elevator = new WPI_TalonSRX(1);
        
        // Elevator High Limit Switch
        elevatorHighLimit = new DigitalInput(5);
        //LiveWindow.addSensor("Elevator", "topElevLimit", elevatortopElevLimit);
        
        //Elevator Low Limit Switch
        elevatorLowLimit = new DigitalInput(1);
        //LiveWindow.addSensor("Elevator", "bottomElevLimit", elevatorbottomElevLimit);
        
        /*
         * INSTANTIATE LIFT IO
         */
        
        //Lift Speed Controller
        lift = new WPI_TalonSRX(5);
        
        // Elevator High Limit Switch
        liftHighLimit = new DigitalInput(3);
        //LiveWindow.addSensor("Elevator", "topElevLimit", elevatortopElevLimit);
        
        //Elevator Low Limit Switch
        //liftLowLimit = new DigitalInput(1);
        //LiveWindow.addSensor("Elevator", "bottomElevLimit", elevatorbottomElevLimit);

        
        /*
         * INSTANTIATE ARMS IO
         */
        
        //Arm Speed Controllers
        /*
        leftArm = new WPI_TalonSRX(9);
        rightArm = new WPI_TalonSRX(8);
        rightArm.setInverted(true);
        rightArm.follow(leftArm); */
        
    }
}
