

package org.usfirst.frc6979.FRC2018.subsystems;

import edu.wpi.first.wpilibj.command.Subsystem;

import org.usfirst.frc6979.FRC2018.RobotMap;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.DigitalInput;


/**
 *
 */
public class Elevator extends Subsystem {

 
<<<<<<< HEAD
    private final DigitalInput elevatorHighLimit = RobotMap.elevatorHighLimit;
    private final WPI_TalonSRX elevator = RobotMap.elevatorElevator;
    private final DigitalInput elevatorLowLimit = RobotMap.elevatorLowLimit;
    
    public boolean elevatorTopActive;
    public boolean elevatorBottomActive;
=======
    private final DigitalInput topElevLimit = RobotMap.elevatorHighLimit;
    private final WPI_TalonSRX elevator = RobotMap.elevatorGear;
    private final DigitalInput evaltorLowLimit = RobotMap.elevatorLowLimit;
>>>>>>> wreckingBall

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Update Elevator limits
    	elevatorTopActive = elevatorHighLimit.get();
    	elevatorBottomActive = elevatorLowLimit.get();
    	

    }

    public void runElevatorUp(double speed) {
    	// Move elevator motor up if not on the upper limit
    	if (!this.elevatorTopActive) {
    		elevator.set(Math.abs(speed));
    	}
    }
    
    public void runElevatorDown(double speed) {
    	// Move elevator motor down if not on the lower limit
    	if (!this.elevatorBottomActive) {
    		elevator.set(-Math.abs(speed));
    	}
    }

}

