package org.usfirst.frc6979.FRC2018.subsystems;

import org.usfirst.frc6979.FRC2018.RobotMap;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

public class Elevator extends Subsystem {

 
    private static final DigitalInput elevatorHighLimit = RobotMap.elevatorHighLimit;
    private final WPI_TalonSRX elevator = RobotMap.elevator;
    private static final DigitalInput elevatorLowLimit = RobotMap.elevatorLowLimit;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    	SmartDashboard.putBoolean("Elevator Top", elevatorHighLimit.get());
    	SmartDashboard.putBoolean("Elevator Bottom", elevatorLowLimit.get());
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
   public static boolean getTopLimit(){
    	return elevatorHighLimit.get();
   }
   
   public void setElevatorSpeed(double speed) {
	   this.elevator.set(speed);
   }
   
   public static boolean getBottomLimit() {
	   return elevatorLowLimit.get();
   }

}

